### ISSUE TITLE
assertion failed in monitor thread at end of select phase

### ISSUE THREAD

**Issue by kostja** [rvncerr/nosql-benchmark#1]
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa54954bcc9 in __GI_raise (sig=sig@entry=6)

```
at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
```

56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007fa54954bcc9 in __GI_raise (sig=sig@entry=6)

```
at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
```
#1  0x00007fa54954f0d8 in __GI_abort () at abort.c:89
#2  0x00007fa549544b86 in __assert_fail_base (

```
fmt=0x7fa549695830 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
assertion=assertion@entry=0x40609a "0", 
file=file@entry=0x406040 "tarantool-c-client/msgpuck.h", 
line=line@entry=1194, 
function=function@entry=0x4069b6 <__PRETTY_FUNCTION__.2812> "mp_decode_map") at assert.c:92
```
#3  0x00007fa549544c32 in __GI___assert_fail (assertion=0x40609a "0",

```
file=0x406040 "tarantool-c-client/msgpuck.h", line=1194, 
function=0x4069b6 <__PRETTY_FUNCTION__.2812> "mp_decode_map")
at assert.c:101
```
#4  0x0000000000401980 in mp_decode_map (data=0x7fa549413d78)

```
at tarantool-c-client/msgpuck.h:1194
```
#5  0x0000000000404ffc in tarantool_request_space_len (

```
connection=0x7fa549513ef0, space=512) at tarantool-c-client/request.c:132
```
#6  0x0000000000405b23 in monitor_proc (arg=0x0)

```
at nosql-benchmark-tarantool.c:92
```
#7  0x00007fa5498e2182 in start_thread (arg=0x7fa549514700)

```
at pthread_create.c:312
```
#8  0x00007fa54960f47d in clone ()

AFAIU it tries to decode input when there is none. mp_decode() should be used only on valid input, it simply asserts on bad input

**Comment by kostja** [comment]
To repeat, you start tarantool, start benchmark, wait till it finishes, then hit ctrl-c in tarantool window to end tarantool
